### ISSUE TITLE
No way to reuse a prepared context

### ISSUE THREAD

**Issue by rkh** [rubyjs/redjs#1]
In Johnson/Lyndon I can do this:
    require 'sinatra'
    set :context, Johnson::Runtime.new
    context.load "some_giant.js"
    get("/") { settings.context.eval "something();" }

Due to having to access the context within a block passed to open, it seems not possible to reuse a previously created an prepared context. You could try to store the context somewhere, but as I understand you will run into issues, especially with the ruby rhino. If there is a way to do something like this, it should be part of the spec. If there is no way, then someone should come up with one.

**Comment by rkh** [comment]
This also seems to somewhat work with the ruby racer, but it's not part of the spec.

**Comment by cowboyd** [comment]
contexts should be re-useable in both the therubyracer and therubyrhino. All you need to do is hold a reference to it. 

cxt = V8::Context.new
cxt = Rhino::Context.new

If they are not, it is definitely a bug. Perhaps you could propose a new testcase in the form of a commit to the redjs spec?

**Comment by rkh** [comment]
Apparently 5a9bb13d9f7b0ee8ab7f hasn't made it to the gem yet.

**Comment by cowboyd** [comment]
Ok, I've amended the spec to reuse references, and actually removed the open() method from the rubyracer. I never liked it anyway :)

Doing this uncovered a segfault which is now fixed. Thanks!
